### ISSUE TITLE
Simplify agent VM deployment

### ISSUE THREAD

**Issue by bekimd-ms** [zyxyoshine/IOStromplus#3]
Currently user has to deploy VMs manually using the provided templates.
The user should be able to deploy VMs from the controller by running simple command. 
They should be able to deploy N VMs in one deployment. 
Something like this:
iostormplus -deployvm -os Windows -number 10 -datadisks 4 -disksize 1TB
iostormplus -deployvm -of Ubuntu -number 10 -datadisks 4 -disksize 1TB

**Comment by zyxyoshine** [comment]
This is a feature that I have been working on recently, but it has been blocked by some VM extension issues.
