### ISSUE TITLE
User should be able to list all the currently provisioned VMs

### ISSUE THREAD

**Issue by bekimd-ms** [zyxyoshine/IOStromplus#4]
User should have a command to list all currently provisioned VMs
Something like this

iostormplus listvm 

VMPool     NumVMs  OS             DataDisks DiskSize 
----------   ----------  -----------  ----------- ---------
WinVMs     10            Windows   4               1TB
LinVMs       10            Ubuntu      4               1TB

**Comment by zyxyoshine** [comment]
Try `IOStormplus agent show`.
Will add disk data and support pool in the next iteration.
