### ISSUE TITLE
Enable PSRemoting on all Windows machines

### ISSUE THREAD

**Issue by bekimd-ms** [zyxyoshine/IOStromplus#8]
Add WinRM port (5986) to inbound NSG rules. 
Include this in custom script for all machines 

$DNSName = $env:COMPUTERNAME 
#Ensure PS remoting is enabled, although this is enabled by default for Azure VMs 
Enable-PSRemoting -Force   
#Create rule in Windows Firewall 
New-NetFirewallRule -Name "WinRM HTTPS" -DisplayName "WinRM HTTPS" -Enabled True -Profile "Any" -Action "Allow" -Direction "Inbound" -LocalPort 5986 -Protocol "TCP"    
#Create Self Signed certificate and store thumbprint 
$thumbprint = (New-SelfSignedCertificate -DnsName $DNSName -CertStoreLocation Cert:\LocalMachine\My).Thumbprint   
#Run WinRM configuration on command line. DNS name set to computer hostname, you may wish to use a FQDN 
$cmd = "winrm create winrm/config/Listener?Address=*+Transport=HTTPS @{Hostname=""$DNSName""; CertificateThumbprint=""$thumbprint""}" 
cmd.exe /C $cmd

**Comment by zyxyoshine** [comment]
All windows VM have enabled PSRemoting  by `winrm quickconfig -q`.
Will improve this in the next iteration.
