### ISSUE TITLE
Monitor status of the agents

### ISSUE THREAD

**Issue by bekimd-ms** [zyxyoshine/IOStromplus#9]
controller should know the stastus of the agents. 
The status can be read from ARM to check if VM is running. 
Agents should reporting heartbeat so controller knows they are alive

**Comment by zyxyoshine** [comment]
Now pre-sync is used to confirm the state of agents is healthy or not.
Will implement heartbeat check later.

**Comment by bekimd-ms** [comment]
If I shut down the test VMs and then restart them, it looks like the agents can not be controlled any more. 
This is the error I am getting: 
Start standard test.
Sending pre-sync request to test VM testvm0(10.0.0.8)
.\IOStormplus.exe : Access is denied.
    + CategoryInfo          : NotSpecified: (Access is denied.:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError

Sending pre-sync request to test VM testvm1(10.0.0.7)
Access is denied.
Sending pre-sync request to test VM testvm2(10.0.0.5)
Access is denied.
Sending pre-sync request to test VM testvm3(10.0.0.6)
Access is denied.
Sending pre-sync request to test VM testvm4(10.0.0.9)
The specified server cannot perform the requested operation.
Sending pre-sync request to test VM testvm5(10.0.0.10)
The specified server cannot perform the requested operation.
Sending pre-sync request to test VM testvm6(10.0.0.11)
The specified server cannot perform the requested operation.
Sending pre-sync request to test VM testvm7(10.0.0.12)
The specified server cannot perform the requested operation.
Waiting for agents response.
